#include "educationalquiz.h"
#include <QtQml>
#include <QThread>
#include "mainapplication.h"
#include "ressources.h"

int EducationalQuiz::s_number_proposals = 4;

/** Constructor with level game
 * @brief QuestionnaireEducatif::QuestionnaireEducatif
 * @param niveauDuJeu the level game
 */
EducationalQuiz::EducationalQuiz(Level* niveauDuJeu):
    GameType(niveauDuJeu)
{
    qsrand(QDateTime::currentDateTime().toTime_t());
}

/** Destructor
 * @brief QuestionnaireEducatif::~QuestionnaireEducatif
 */
EducationalQuiz::~EducationalQuiz()
{
    m_currentQuestion = NULL;
    qDeleteAll(m_questionsAsked);
}

/**  Getter proposal1
 * @brief QuestionnaireEducatif::getProposal1
 * @return the proposal1 in the m_listProposals.
 */
const QString EducationalQuiz::getProposal1()
{
    return m_listProposals.at(0);
}

/**  Getter proposal2
 * @brief QuestionnaireEducatif::getProposal2
 * @return the proposal2 in the m_listProposals.
 */
const QString EducationalQuiz::getProposal2()
{
    return m_listProposals.at(1);
}

/**  Getter proposal3
 * @brief QuestionnaireEducatif::getProposal3
 * @return the proposal3 in the m_listProposals.
 */
const QString EducationalQuiz::getProposal3()
{
    return m_listProposals.at(2);
}

/**  Getter proposal4
 * @brief QuestionnaireEducatif::getProposal4
 * @return the proposal4 in the m_listProposals.
 */
const QString EducationalQuiz::getProposal4()
{
    return m_listProposals.at(3);
}

/** Getter of the current question
 * @brief QuestionnaireEducatif::getCurrentQuestion
 * @return the current question
 */
Question* EducationalQuiz::getCurrentQuestion()
{
    return m_currentQuestion;
}

/** Setter of list proposals, autogenerated with the question operand
 * @brief QuestionnaireEducatif::setListProposals
 */
void EducationalQuiz::setListProposals()
{
    m_listProposals.clear();

    QString result = m_currentQuestion->getResult();
    QString propo = m_currentQuestion->getResult();

    int index = qrand() % ((s_number_proposals) - 0) + 0;

    for(int i=1; i < s_number_proposals; i++)
    {
        while(!propo.compare(result) || m_listProposals.contains(propo))
        {
            propo = m_currentQuestion->getProposal();
        }
        m_listProposals.append(propo);
    }
    m_listProposals.insert(index, result);
}

/** Launcher of game
 * @brief QuestionnaireEducatif::launchGame
 */
void EducationalQuiz::launchGame()
{
    launchQuestion();
}

/** Launcher of question
 * @brief QuestionnaireEducatif::launchQuestion
 */
void EducationalQuiz::launchQuestion()
{
    emit answerTrait();

    m_currentQuestion = this->buildQuestion();
    m_questionsAsked.append(m_currentQuestion);
    MainApplication::s_view->rootContext()->setContextProperty("question", m_currentQuestion);

    setListProposals();
    newQuestion();
}

/** Method to emit new question
 * @brief QuestionnaireEducatif::newQuestion
 */
void EducationalQuiz::newQuestion()
{
    emit proposal1Changed();
    emit proposal2Changed();
    emit proposal3Changed();
    emit proposal4Changed();
}

/** Trait response if right or wrong
 * @brief QuestionnaireEducatif::traitAnswer
 * @param indexAnswer the index of answer
 */
void EducationalQuiz::traitAnswer(int indexAnswer)
{
    emit answerTrait();

    m_listResetAnswers.clear();

    if(this->isQuiz())
    {
        traitAnswerCalculation(indexAnswer);
    }
    else
    {
        //faire autre traitement.
    }
}

/** Trait response if right or wrong
 * @brief QuestionnaireEducatif::traitAnswer
 * @param indexAnswer the index of answer
 */
void EducationalQuiz::traitAnswerCalculation(int indexAnswer)
{
    int result = m_currentQuestion->getResult().toInt();
    int indexResult = m_listProposals.indexOf(QString::number(result));

    //Gestion du résultat
    if(m_listProposals.at(indexAnswer-1).toInt() == result)
    {
        //Réponse correcte
        emit answerRight(indexAnswer);

        //add point au profil
        emit incrementScore(this->s_incremental_score * 2);
    }
    else
    {
        //Réponse fausse
        emit answerWrong(indexAnswer);
        emit answerRight(indexResult + 1);
        emit decrementScore(this->s_incremental_score);

        m_listResetAnswers.append(indexResult + 1);
    }

    m_listResetAnswers.append(indexAnswer);
    //add stat question
}

/** Method for emit reset answers
 * @brief QuestionnaireEducatif::answersReset
 */
void EducationalQuiz::answersReset()
{
    for(int index : m_listResetAnswers)
    {
        emit resetAnswer(index);
    }
}
