#ifndef RESSOURCES_H
#define RESSOURCES_H

#include <QString>

const QString MODE_FLASHCARD = "FLASHCARD";
const QString MODE_DENOMBREMENT = "DENOMBREMENT";
const QString MODE_COULEUR = "COULEUR";
const QString MODE_ADDITION = "ADDITION";
const QString MODE_SOUSTRACTION = "SOUSTRACTION";
const QString MODE_MULTIPLICATION = "MULTIPLICATION";
const QString MODE_DIVISION = "DIVISION";

const int INCREMENTAL_SCORE_ADDITION = 1;
const int INCREMENTAL_SCORE_SOUSTRACTION = 1;
const int INCREMENTAL_SCORE_MULTIPLICATION = 2;
const int INCREMENTAL_SCORE_DIVISION = 2;

#endif // RESSOURCES_H
