#ifndef RESSOURCES_H
#define RESSOURCES_H

#include <QString>

const QString PATH_DATA_BASE = "drdonut.db.sqlite";

const QString MODE_FLASHCARD = "FLASHCARD";
const QString MODE_MELE = "ALL";
const QString MODE_ENUMERATION = "ENUMERATION";
const QString MODE_COLOR = "COLOR";
const QString MODE_ADDITION = "ADDITION";
const QString MODE_SUBTRACTION = "SUBTRACTION";
const QString MODE_MULTIPLICATION = "MULTIPLICATION";
const QString MODE_DIVISION = "DIVISION";

const int INCREMENTAL_SCORE_ADDITION = 1;
const int INCREMENTAL_SCORE_SUBTRACTION = 1;
const int INCREMENTAL_SCORE_MULTIPLICATION = 2;
const int INCREMENTAL_SCORE_DIVISION = 2;

#endif // RESSOURCES_H
